### ISSUE TITLE
Deb Package

### ISSUE THREAD

**Issue by aldmbmtl** [AcademySoftwareFoundation/xstudio#36]
Hello!

I am currently setting this up to be installed as a deb package, that way it can be more easily installed for us on Ubuntu 22.04. I have opened up our work on this topic on our repository here: [Juno Labs](https://github.com/juno-fx/labs-packages/tree/continued/deb/xstudio). I have packaged up all the required libraries into deb packages as well in this directory: [Packages](https://github.com/juno-fx/labs-packages/tree/continued/deb). 

The build process does compile the libs in docker containers and then ship out the `.deb` files for us to use when we build our workstations (which are also containers).

With the back story out of the way...

I have managed to get xStudio to compile on a workstation and run perfectly fine when I built it from source and don't package it. Once I package it, it seems to have the `preference` directory hard coded into it's start up process.

```
#26 0.915 [2023-03-27 22:06:04.038] [xstudio] [info] XStudio logging started.
#26 0.915 [2023-03-27 22:06:04.038] [xstudio] [warning] Failed preference_load_defaults from path /juno/xstudio/build/bin/preference with error filesystem error: directory iterator cannot open directory: No such file or directory [/juno/xstudio/build/bin/preference].
#26 0.915 [2023-03-27 22:06:04.038] [xstudio] [error] Failed to load application preferences /juno/xstudio/build/bin/preference
```

As you can see, it is loading the preferences from the original build location `/juno/xstudio/build/bin/preference`. 

When I build the `.deb` package, I am taking the `build/bin` folder and dropping it into `/opt/xstudio`. So the `preference` directory actually exists like this `/opt/xstudio/preference` after installed. 

So I did some further debugging, and after running `-h` on `xstudio` after it is installed, it kicked back an option `--pref`. According to the information provided, it should allow me to pass in the following `xstudio --pref /opt/xstudio/preference/` and it should work I would think. Instead, it seems to completely ignore it. I also tried `xstudio --pref=/opt/xstudio/preference/` and even went crazy with it and added `xstudio --pref=[/opt/xstudio/preference/]`. Then finally, I sent out a yolo and wrapped it all in quotes `xstudio --pref=["/opt/xstudio/preference/"]`. I am quite comfortable in linux so I know that for the most part, the square brackets are just examples and shouldn't be included, but I figured I would try.

 I did some further debugging, I can actually completely recreate the build directory on a fresh container, and symlink it to `/opt/xstudio/preference` and then xStudio will launch no problem. 
 
 ```
 /juno/xstudio/build/bin/preference -> /opt/xstudio/preference
 ```
 
 Here are some links to the container I am building to do this. p.s. these are not the workstations, these are just the build containers used to output the `.deb` files. Our workstation containers are in private repos.

Launch command for testing
https://github.com/juno-fx/labs-packages/blob/continued/deb/xstudio/Dockerfile#L106

Build file
https://github.com/juno-fx/labs-packages/blob/continued/deb/xstudio/build.sh

Juno Dependencies
https://github.com/juno-fx/labs-packages/blob/continued/deb/xstudio/juno-deps.sh

Please forgive the relative mess that the files are in. I am still the the phase of getting everything working and it will be cleaned up before getting merged into `main` for Juno and even the world to use if they want :smiley: 

Please let me know if I can provide any other information!

**Comment by alatdneg** [comment]
From memory this is controlled by the XSTUDIO_ROOT env var, you probably need a shell script launcher for xStudio that sets this value to your install dir (where the plugins / libraries / preferences live). /usr/local/share/xstudio ?

It looks like you're not using ninja install. That'll create the output you'll want to use for deployments.

By default it builds something that is helpful for debugging, hence the odd location of files.

**Comment by aldmbmtl** [comment]
Thanks for the quick response! 

I am just building it from the docs in the Ubuntu docs. Should I be doing it another way? I will also give that XSTUDIO_ROOT var a test as soon as I can.

Thanks!

**Comment by aldmbmtl** [comment]
This fixed the launch issue, but xstudio hard crashes the moment you click to open a playlist. Sadly we decided to switch away to something else :disappointed:. Thank you for all of your hard work though! It really does take a lot to open source a project like this and I respect it. We will keep an eye on it as time goes on.
