### ISSUE TITLE
How to use ShotGun?

### ISSUE THREAD

**Issue by zavinator** [AcademySoftwareFoundation/xstudio#42]
Hi, I've compiled the xstudio in RockyLinux including the Shotgun plugin. 
But I really don't know how to use it - there is no error message, but I don't see any Shotgun related interface.
Is there any option to enable it?

**Comment by alatdneg** [comment]
There are two parts, the shotgun_client , which is a c++ wrapper around the shotgun REST API which can be used by anyone writing there own code to interact with shotgun. And the DNEG shotgun plugin, this is specific to our workflows and shotgun database schema so won't be usable outside of DNEG, we include it as a reference on how to go about writing your own plugin.

**Comment by zavinator** [comment]
Ok, thanks
